# Dataframe

In [2]:
import pandas as pd

In [3]:
from numpy.random import randn

In [5]:
df  = pd.DataFrame(randn(5,4),['A','B','C','D','E'], ['W','X','Y','Z'])
df

          W         X         Y         Z
A -0.372658  1.754495  0.507104 -0.282495
B -0.378513  0.575466 -2.012051 -0.381453
C -1.444165  0.646565 -0.777054  0.115287
D  1.568436 -0.411680 -0.051486  0.168959
E  0.140624  0.522233 -1.403687 -0.172420

In [8]:
type(df['W'])

pandas.core.series.Series

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.W

A   -0.372658
B   -0.378513
C   -1.444165
D    1.568436
E    0.140624
Name: W, dtype: float64

In [11]:
df[['W','X']]

          W         X
A -0.372658  1.754495
B -0.378513  0.575466
C -1.444165  0.646565
D  1.568436 -0.411680
E  0.140624  0.522233

In [12]:
df['new'] = [1,2,3,4,5]

In [13]:
df

          W         X         Y         Z  new
A -0.372658  1.754495  0.507104 -0.282495    1
B -0.378513  0.575466 -2.012051 -0.381453    2
C -1.444165  0.646565 -0.777054  0.115287    3
D  1.568436 -0.411680 -0.051486  0.168959    4
E  0.140624  0.522233 -1.403687 -0.172420    5

In [15]:
df.drop('new', axis=1, inplace=True)

In [16]:
df

          W         X         Y         Z
A -0.372658  1.754495  0.507104 -0.282495
B -0.378513  0.575466 -2.012051 -0.381453
C -1.444165  0.646565 -0.777054  0.115287
D  1.568436 -0.411680 -0.051486  0.168959
E  0.140624  0.522233 -1.403687 -0.172420

In [17]:
df.drop('E')

          W         X         Y         Z
A -0.372658  1.754495  0.507104 -0.282495
B -0.378513  0.575466 -2.012051 -0.381453
C -1.444165  0.646565 -0.777054  0.115287
D  1.568436 -0.411680 -0.051486  0.168959

In [18]:
df.shape

(5, 4)

In [20]:
df.loc[['A','C']]

          W         X         Y         Z
A -0.372658  1.754495  0.507104 -0.282495
C -1.444165  0.646565 -0.777054  0.115287

In [22]:
df.iloc[[1,3]]

          W         X         Y         Z
B -0.378513  0.575466 -2.012051 -0.381453
D  1.568436 -0.411680 -0.051486  0.168959

In [23]:
df

          W         X         Y         Z
A -0.372658  1.754495  0.507104 -0.282495
B -0.378513  0.575466 -2.012051 -0.381453
C -1.444165  0.646565 -0.777054  0.115287
D  1.568436 -0.411680 -0.051486  0.168959
E  0.140624  0.522233 -1.403687 -0.172420

In [25]:
df[df > 0]

          W         X         Y         Z
A       NaN  1.754495  0.507104       NaN
B       NaN  0.575466       NaN       NaN
C       NaN  0.646565       NaN  0.115287
D  1.568436       NaN       NaN  0.168959
E  0.140624  0.522233       NaN       NaN

In [26]:
df[df['W'] > 0]

          W         X         Y         Z
D  1.568436 -0.411680 -0.051486  0.168959
E  0.140624  0.522233 -1.403687 -0.172420

In [27]:
df[(df['W'] > 0 ) & (df['X'] < 0)]

          W        X         Y         Z
D  1.568436 -0.41168 -0.051486  0.168959

In [28]:
df[(df['W'] > 0 ) | (df['X'] < 0)]

          W         X         Y         Z
D  1.568436 -0.411680 -0.051486  0.168959
E  0.140624  0.522233 -1.403687 -0.172420

In [29]:
df

          W         X         Y         Z
A -0.372658  1.754495  0.507104 -0.282495
B -0.378513  0.575466 -2.012051 -0.381453
C -1.444165  0.646565 -0.777054  0.115287
D  1.568436 -0.411680 -0.051486  0.168959
E  0.140624  0.522233 -1.403687 -0.172420

In [32]:
df.reset_index(drop=True)

          W         X         Y         Z
0 -0.372658  1.754495  0.507104 -0.282495
1 -0.378513  0.575466 -2.012051 -0.381453
2 -1.444165  0.646565 -0.777054  0.115287
3  1.568436 -0.411680 -0.051486  0.168959
4  0.140624  0.522233 -1.403687 -0.172420

In [33]:
new_index = 'AA BB CC DD EE'.split()

In [34]:
df['new_index'] = new_index

In [35]:
df

          W         X         Y         Z new_index
A -0.372658  1.754495  0.507104 -0.282495        AA
B -0.378513  0.575466 -2.012051 -0.381453        BB
C -1.444165  0.646565 -0.777054  0.115287        CC
D  1.568436 -0.411680 -0.051486  0.168959        DD
E  0.140624  0.522233 -1.403687 -0.172420        EE

In [36]:
df.set_index('new_index')

                  W         X         Y         Z
new_index
AA        -0.372658  1.754495  0.507104 -0.282495
BB        -0.378513  0.575466 -2.012051 -0.381453
CC        -1.444165  0.646565 -0.777054  0.115287
DD         1.568436 -0.411680 -0.051486  0.168959
EE         0.140624  0.522233 -1.403687 -0.172420

In [37]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [39]:
df = pd.DataFrame(randn(6,2),hier_index, ['A','B'])
df

             A         B
G1 1 -1.851491  0.416364
   2 -1.166693 -0.098909
   3  0.251904  1.465342
G2 1  0.241715 -1.480578
   2  0.670342  2.073403
   3  1.425565 -0.132264

In [41]:
df.loc['G1'].loc[2]

A   -1.166693
B   -0.098909
Name: 2, dtype: float64

In [43]:
df.index.names = ['Groups','num']

In [44]:

df

                   A         B
Groups num
G1     1   -1.851491  0.416364
       2   -1.166693 -0.098909
       3    0.251904  1.465342
G2     1    0.241715 -1.480578
       2    0.670342  2.073403
       3    1.425565 -0.132264

In [51]:
df.loc['G2'].iloc[1,1]

np.float64(2.0734031778791993)

In [55]:
df.xs(1,level='num')

               A         B
Groups
G1     -1.851491  0.416364
G2      0.241715 -1.480578