## Missing values

In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [6]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [7]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [8]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [13]:
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [14]:
df.fillna(value='Filled')

        A       B  C
0     1.0     5.0  1
1     2.0  Filled  2
2  Filled  Filled  3

In [15]:
df.fillna(df.mean())

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3