In [2]:
import pandas as pd

s1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'], 
        'marks': [200, 210, 190, 222, 199]})

s2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'], 
        'marks': [201, 200, 198, 219, 201]})

In [4]:
s1

  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199

In [5]:
s2

  student_id              name  marks
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201

## join

In [8]:
pd.concat([s1,s2])

  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201

In [9]:
pd.concat([s1,s2], axis=1)

  student_id              name  marks student_id              name  marks
0         S1  Danniella Fenton    200         S4  Scarlette Fisher    201
1         S2      Ryder Storey    210         S5  Carla Williamson    200
2         S3      Bryce Jensen    190         S6       Dante Morse    198
3         S4         Ed Bernal    222         S7    Kaiser William    219
4         S5       Kwame Morin    199         S8   Madeeha Preston    201

## merge

In [11]:
s1.merge(s2, on='student_id')

  student_id       name_x  marks_x            name_y  marks_y
0         S4    Ed Bernal      222  Scarlette Fisher      201
1         S5  Kwame Morin      199  Carla Williamson      200

In [12]:
s1.merge(s2, on='student_id', how='outer')

  student_id            name_x  marks_x            name_y  marks_y
0         S1  Danniella Fenton    200.0               NaN      NaN
1         S2      Ryder Storey    210.0               NaN      NaN
2         S3      Bryce Jensen    190.0               NaN      NaN
3         S4         Ed Bernal    222.0  Scarlette Fisher    201.0
4         S5       Kwame Morin    199.0  Carla Williamson    200.0
5         S6               NaN      NaN       Dante Morse    198.0
6         S7               NaN      NaN    Kaiser William    219.0
7         S8               NaN      NaN   Madeeha Preston    201.0