In [1]:
import pandas as pd

In [2]:
ser = pd.Series([1,2,3,4,5])

In [3]:
ser

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
ser.tolist()

[1, 2, 3, 4, 5]

In [7]:
data = {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
df = pd.DataFrame(data)

In [8]:
df

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

In [9]:
df = pd.DataFrame(data, index='a b c d e'.split())
df

    X   Y   Z
a  78  84  86
b  85  94  97
c  96  89  96
d  80  83  72
e  86  86  83

In [10]:
df = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_Birth': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'weight': [35, 32, 33, 30, 31, 32],
    'address': ['street1', 'street2', 'street3', 'street1', 'street2', 'street4'],
    't_id':['t1', 't2', 't3', 't4', 't5', 't6']})

In [11]:
df

  school_code class            name date_Of_Birth  weight  address t_id
0        s001     V  Alberto Franco    15/05/2002      35  street1   t1
1        s002     V    Gino Mcneill    17/05/2002      32  street2   t2
2        s003    VI     Ryan Parkes    16/02/1999      33  street3   t3
3        s001    VI    Eesha Hinton    25/09/1998      30  street1   t4
4        s002     V    Gino Mcneill    11/05/2002      31  street2   t5
5        s004    VI    David Parkes    15/09/1997      32  street4   t6

In [13]:
df.index.values

array([0, 1, 2, 3, 4, 5])

In [14]:
df.set_index('t_id')

     school_code class            name date_Of_Birth  weight  address
t_id
t1          s001     V  Alberto Franco    15/05/2002      35  street1
t2          s002     V    Gino Mcneill    17/05/2002      32  street2
t3          s003    VI     Ryan Parkes    16/02/1999      33  street3
t4          s001    VI    Eesha Hinton    25/09/1998      30  street1
t5          s002     V    Gino Mcneill    11/05/2002      31  street2
t6          s004    VI    David Parkes    15/09/1997      32  street4